### ISSUE TITLE
How should redeploys work with swapped EC2s?

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3_deploy#13]
@afred: Not clear to me how this will work when we're swapping the EC2s: I think there will need to be a dependency on aws-wrapper, because it's the only machinery that can determine the IP of the instance behind the demo load balancer ... but you might have something else in mind?

**Comment by afred** [comment]
per in-person discussion, we'll parameterize the host IP address to use an env var. See #4.

Then there can be a little behind the scenes magic in [`deploy.sh`](https://github.com/WGBH/openvault3/blob/master/scripts/deploy.sh) that sets this value for the user, using code from `aws-wrapper` to retrieve the correct host for the current "demo" server.
