### ISSUE TITLE
Be more explicit about which file to use when running `cap [stage] ingest:run`

### ISSUE THREAD

**Issue by afred** [WGBH/openvault3_deploy#31]
Currently, if you want to run `cap [stage] ingest:run`, you are required to supply a path to local pbcore file using `OV_PBCORE` env var.

The script will then use the file basename of `OV_PBCORE` to search the remote machine for a matching filename in a predetermined location. This is too magical.

We should either require that `cap [demo] ingest:run` takes a parameter specifying the path to the remote file to use. The downside to this is that the user needs to know exactly where the remote file was uploaded.

Or... we could have `cap [demo] ingest:run` always look for the same file, in the same place. The downside to this is that the ingest params need to know whether its looking at a zipped file, or a single file, or a directory.

not sure which is better yet.

**Comment by mccalluc** [comment]
Is there a reason capistrano couldn't do the scp?

**Comment by afred** [comment]
@mccalluc no, it can move files between local and remote, no problem.

The problem is that this is confusing: `cap  demo ingest:run OV_PBCORE=path/to/pbcore.zip`

It's confusing because file `path/to/pbcore.zip` is not actually being used here. It's just using the basename `pbcore.zip` to check for a remote file named the same thing, but at a different path: `/var/www/openvault/current/ingest_data/`

**Comment by afred** [comment]
closed by #41
