### ISSUE TITLE
Add task to download log

### ISSUE THREAD

**Issue by mccalluc** [WGBH/openvault3_deploy#32]
>
`+1 for adding something like cap [stage] ingest:download_log.`

... and perhaps just exit with non-zero status if it is still running.

or email the log... probably don't need both.

**Comment by afred** [comment]
**Done when** there is a task that downloads the most recent ingest log.

**Comment by afred** [comment]
after discussion with @Muraszko accessing the logs is not a problem, so we don't need a special cap task for it. Closing.
