### ISSUE TITLE
Add log directory to list of directories shared between deploys.

### ISSUE THREAD

**Issue by afred** [WGBH/openvault3_deploy#49]
Pros:
  1. we don't lose logs when old deploys are deleted
  2. can see all logs in one location, without having to know to look into past releases.

Cons:
  1. Would conflate www logs between releases. So you might end up with a request that causes an error in one part of the log, that does not cause an error in another part of the log. This could be confusing if you are parsing the log trying to track down errors.

@mccalluc I think pros > cons here, agree?

**Comment by mccalluc** [comment]
Yeah, that seems reasonable to me. Would there be any way to do a log roll with the deploy, so that things are kept separate?

**Comment by afred** [comment]
closed by #55
